### PR TITLE
Initial commit of rsfmodel dashboard

### PR DESCRIPTION
**Pull request by jrleeman**
We may have to do some work here and there - let me know any thoughts.

### CODE REVIEW

**Comment by krischer** [comment]
Cool - thanks a lot! I manually merged it and added some missing things to the dockerfile. Additionally I added the seimo-live header, some advertisement for your toolkits and introductions on how to see the dashboard. I also converted the notebook to Python 3 - nothing do to - just make sure its saved with Python 3, otherwise it will launch with a Python 2 kernel which as of now has almost no packages installed.

Its already live at the server. Please have a look at let me know if something is missing. Apart from some small formatting issues and some warnings it looks pretty good to me but who am I to say?

Unfortunately people have to do two steps before they can see the dashboard - I'm not sure there is a way to automatically do that once the notebook is opened?

**Comment by jrleeman** [comment]
Wow! Works great on this end. Let me ping some dashboard folks and see if there is any magic (literal or figurative) we can do to go it to run and be in dashboard mode.

**Comment by krischer** [comment]
Great :-) There is a separate dashboard server that according to some issues on github also appears to have a way to somehow integrate with the tmpnb server (which seismo-live uses). From a quick search I could not see a simple way to get a single tmpnb server to serve dashboards as well as the normal notebooks. But maybe it possible - or some hook that run when the notebook starts would also do the trick.

**Comment by jrleeman** [comment]
I tried the dashboard server on AWS without much luck, but that’s probably my ignorance of AWS.

**Comment by jrleeman** [comment]
They say it's not feasible - to stand up a dashboard server. Maybe we should just put a few instructions on to tell people how to get it running? I'll play with a dashboard server at some point, but it'll be a few weeks.

**Comment by krischer** [comment]
There already are a couple of instructions in the yellow box telling people how to launch the dashboard. I think thats good enough for now :smile:

Thanks again! I'm happy to take whatever else you have!

**Pull request closed without merging**
