### PR TITLE
try to fix mangled images in PPSD notebook

### PR DESCRIPTION
**Pull request by megies**
hope to fix broken images in PPSD notebooks..

### CODE REVIEW

**Comment by krischer** [comment]
Uhh..even with Python 3 ;-) Thanks!

**Comment by megies** [comment]
> Uhh..even with Python 3 ;-) Thanks!

Saved from within seismo-live.org tmpnbserver.. ;-)

Did you update the live instance already? Right now images are still broken on the server..

**Comment by krischer** [comment]
Yea..I cannot get it to work. Also does not work on a local conda installation of mine.

**Comment by megies** [comment]
Can you try this one on your computer? 

[Probabilistic Power Spectral Densities.ipynb.txt](https://github.com/krischer/seismo_live/files/279654/Probabilistic.Power.Spectral.Densities.ipynb.txt)

**Comment by krischer** [comment]
also does not work (at least on my machine). What version of the dependencies are you running? Mine:

```
ipywidgets                4.1.1                    py35_0    defaults
jupyter                   1.0.0                    py35_2    defaults
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py35_0    defaults
jupyter_console           4.1.1                    py35_0    defaults
jupyter_core              4.1.0                    py35_0    defaults
matplotlib                1.5.1               np110py35_0    defaults
```

**Comment by megies** [comment]
> also does not work (at least on my machine). What version of the dependencies are you running? Mine:



> Saved from within seismo-live.org tmpnbserver.. ;-)

Dependencies of server..

**Comment by krischer** [comment]
Can you open it (without uploading) on your machine? If yes - I'll just update the server once again and we'll see what happens ;-)

**Comment by megies** [comment]
Nah.. you're right, doesn't work for me either (in my Python2 Jupyter). Also just seeing those Javascript messages.. So embedded images probably don't work with `nbagg`?

**Comment by krischer** [comment]
Yea I guess so :-( According to some internet searches it should work when closing the figure but I also cannot get it to work. So I guess we cannot use the `nbagg` backend?

**Pull request merged**
