### PR TITLE
Convert everything to Jupytext

### PR DESCRIPTION
**Pull request by krischer**
Also the beginnings of a new workflow how to do things.

### CODE REVIEW

**Comment by megies** [comment]
@krischer @sebnoe I don't want to be overly pedantic and I understand you wanted to keep working on this while the docker/binder setup was still in works, but #36 was basically copy-paste hijacked here. If people are happy with #36 please comment there and it can be merged and we don't have to have duplicate code across multiple PRs then.

**Comment by sebnoe** [comment]
Sorry @megies, my bad. I was experimenting with the binder repository to
see how it reacts. I still have trouble to understand how the
binder-cache works, but we can talk about this on thursday.

Am 05.11.2019 11:33, schrieb Tobias Megies:

> @krischer [1] @sebnoe [2] I don't want to be overly pedantic and I understand you wanted to keep working on this while the docker/binder setup was still in works, but #36 [3] was basically copy-paste hijacked here. If people are happy with #36 [3] please comment there and it can be merged and we don't have to have duplicate code across multiple PRs then. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [4], or unsubscribe [5].
 

Links:
------
[1] https://github.com/krischer
[2] https://github.com/sebnoe
[3] https://github.com/krischer/seismo_live/pull/36
[4]
https://github.com/krischer/seismo_live/pull/33?email_source=notifications&amp;email_token=ALCUY7YOBL762I2FN2U7QXTQSFDY5A5CNFSM4I5OUVM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDCL4VY#issuecomment-549764695
[5]

**Comment by krischer** [comment]
@sebnoe It would also be helpful if you branch off here and work on a different branch and we merge once everything is ready. Multiple people working on a single branch usually results in conflicts that have to be resolved all the time. If we work on different branches we only have to do it once.

**Comment by megies** [comment]
@sebnoe no big deal, we can handle it, just as a heads up. And maybe should focus on getting the old stuff running before adding new stuff, it might get confusing otherwise

**Pull request merged**
